# Generated by Django 5.2 on 2025-04-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('guardianphone', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='student_pics/')),
                ('sroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
