# Generated by Django 5.2 on 2025-04-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('section', models.CharField(choices=[('Remove', 'Remove'), ('Add', 'Add')], max_length=20)),
                ('section_name_time', models.CharField(blank=True, max_length=10, null=True)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
