# Generated by Django 5.2 on 2025-04-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcard',
            name='cou_code',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='cre',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='prog',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='seme',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='sess',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='tit',
        ),
    ]
