# Generated by Django 5.2 on 2025-04-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_admitcard_cou_code_remove_admitcard_cre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('total_att_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_earn_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=10, null=True)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
