# Generated by Django 5.2 on 2025-05-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_totalresult_batch_alter_totalresult_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Tuition(mid)', 'Tuition(mid)'), ('Admission', 'Admission'), ('Registration', 'Registration'), ('Late Fee', 'Late Fee'), ('Retake Fee', 'Retake Fee'), ('Other', 'Other')], max_length=50),
        ),
    ]
