# Generated by Django 5.2 on 2025-05-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_waiver', models.CharField(blank=True, max_length=100, null=True)),
                ('s_due_date', models.DateField()),
                ('s_payment_type', models.CharField(choices=[('Tuition(mid)', 'Tuition(mid)'), ('Admission', 'Admission'), ('Registration', 'Registration'), ('Late Fee', 'Late Fee'), ('Retake Fee', 'Retake Fee'), ('Other', 'Other')], max_length=50)),
                ('s_total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('s_total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('s_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('s_payment_date', models.DateField()),
                ('s_transaction_id', models.CharField(max_length=100, unique=True)),
                ('s_status', models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10)),
                ('s_remarks', models.TextField(blank=True, null=True)),
                ('s_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
