# Generated by Django 5.2 on 2025-05-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_payment_payment_date_studentpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
