# Generated by Django 5.2 on 2025-05-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_waiver', models.CharField(blank=True, max_length=100, null=True)),
                ('t_due_date', models.DateField()),
                ('t_payment_type', models.CharField(choices=[('Tuition(mid)', 'Tuition(mid)'), ('Admission', 'Admission'), ('Registration', 'Registration'), ('Late Fee', 'Late Fee'), ('Retake Fee', 'Retake Fee'), ('Other', 'Other')], max_length=50)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_payment_date', models.DateField()),
                ('t_transaction_id', models.CharField(max_length=100, unique=True)),
                ('t_status', models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10)),
                ('t_remarks', models.TextField(blank=True, null=True)),
                ('t_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
