# Generated by Django 5.2 on 2025-05-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_totalpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPayment',
        ),
    ]
