# Generated by Django 5.2 on 2025-05-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_finalpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalPayment',
        ),
    ]
