# Generated by Django 5.2 on 2025-05-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_delete_totalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_waiver_persent', models.CharField(blank=True, max_length=100, null=True)),
                ('l_due_date', models.DateField()),
                ('l_fee_type', models.CharField(choices=[('1st Installment Registration', '1st Installment Registration'), ('2nd Installment 30% of the Tuition Fees', '2nd Installment 30% of the Tuition Fees'), ('3rd Installment 30% of the Tuition Fee(Mid term)', '3rd Installment 30% of the Tuition Fee(Mid term)'), ('4th Installment 40% of the Tuition Fee(Final)', '4th Installment 40% of the Tuition Fee(Final)'), ('Late Fees', 'Late Fees')], max_length=200)),
                ('l_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_payment_type', models.CharField(choices=[('Tuition(Mid Term)', 'Tuition(Mid Term)'), ('Tuition(Final)', 'Tuition(Final)'), ('Student Payment', 'Student Payment'), ('Registration', 'Registration'), ('Late Fees', 'Late Fees'), ('Repeat Exam Fee', 'Repeat Exam Fee'), ('Additional Waiver', 'Additional Waiver'), ('Caution money', 'Caution money'), ('Admission and varificatin fees', 'Admission and varificatin fees'), ('Other', 'Other')], max_length=100)),
                ('l_waiver_taka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_payment_date', models.DateField()),
                ('l_transaction_id', models.CharField(max_length=100, unique=True)),
                ('l_status', models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10)),
                ('l_remarks', models.TextField(blank=True, null=True)),
                ('l_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
