# Generated by Django 5.2 on 2025-05-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_lastpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalPayment',
        ),
    ]
