# Generated by Django 5.2 on 2025-05-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_finalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fexam', models.CharField(choices=[('Mid', 'Mid'), ('Final', 'Final')], max_length=20)),
                ('fschedule', models.CharField(blank=True, max_length=100, null=True)),
                ('fbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitcard_bill', to='app1.lastpayment')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_student', to='app1.student')),
                ('fsemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_semester', to='app1.studentinfo')),
            ],
        ),
    ]
