# Generated by Django 5.2 on 2025-05-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_finaladmitcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmitCard',
        ),
    ]
