# Generated by Django 5.2.1 on 2025-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpayment',
            name='l_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
